// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrD22vjntcicWgB2ezHg1vHskZvW0jGjI',
    appId: '1:429639682739:web:559f7ef2fd578e6640fec6',
    messagingSenderId: '429639682739',
    projectId: 'novel-starter',
    authDomain: 'novel-starter.firebaseapp.com',
    storageBucket: 'novel-starter.firebasestorage.app',
    measurementId: 'G-6QPDRG6DZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYqjmnWfNF_br8j_EY95ETaiuoiwibMM',
    appId: '1:429639682739:android:89071e39b87df9a540fec6',
    messagingSenderId: '429639682739',
    projectId: 'novel-starter',
    storageBucket: 'novel-starter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfn4pQB0WsqC2xe-OzOSyETUkDftbTK9s',
    appId: '1:429639682739:ios:7c4862fce1ec73e240fec6',
    messagingSenderId: '429639682739',
    projectId: 'novel-starter',
    storageBucket: 'novel-starter.firebasestorage.app',
    iosBundleId: 'com.example.novelStarter',
  );
}
